### ISSUE TITLE
Phone compatibility

### ISSUE THREAD

**Issue by Pantus** [FredJul/Kiddie-Parental-Control#1]
Hey there, I'm wondering why isn't the Xiaomi Redmi Note 4 incompatible with the app. Is there a specific reason for it do you just need to update, the supported devices list?

**Comment by FredJul** [comment]
Hi,

First of all sorry for the late reply. Concerning your question, please
note that all xiaomi/huawei/honor devices has been blocked since they
modify Android and make Heimdall not working properly.

I actually didn't really had the choice and would have prefer to not do
this.

Regards,
Fred
