### ISSUE TITLE
Using the app on LineageOS without gapps installed

### ISSUE THREAD

**Issue by andisk4** [FredJul/Kiddie-Parental-Control#2]
Hi there, I'd like to use your app on a LineageOS phone, that has no google-apps installed. Is there an other way to buy, and getting it?

**Comment by FredJul** [comment]
I'm sorry but I have no support for device without gapps and will certainly never have.

However it may actually works, if you retrieve the APK on websites like https://apkpure.com/fr/kiddie-parental-control/net.frju.heimdall and install it you may be able to use all the free features, but I honestly don't know and would suggest to carefully check the website you use to DL the apk (I don't know if APKpure is thruthwortly and do not modify the APKs to add spywares)

**Comment by andisk4** [comment]
Thanks for your quick answer!
Is there any easy way for you (obviously there isn't for me) to check the integrity of a third party provided apk? The use of any non-free feature is only available through gapps, paying the fee over paypal is not an option?

**Comment by FredJul** [comment]
I can't think of a obvious way to check that, I would suggest to do research on their reputation.

As you said, the non-free features are only available through gapps (for several reasons), I'm sorry but paypal is not an option here and will certainly never be.
